server:
  port: 9090

spring:
  application:
    name: app-service

logging:
  file:
    path: ./app/logs
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html